<?php

namespace ContainerVlIiqx7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminformationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\admin\AdminformationController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminformationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/admin/AdminformationController.php';

        $container->services['App\\Controller\\admin\\AdminformationController'] = $instance = new \App\Controller\admin\AdminformationController(($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminformationController', $container));

        return $instance;
    }
}
