<?php

namespace ContainerWjKZSvZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.j1iESqK.App\Entity\Playlist' shared service.
     *
     * @return \App\Entity\Playlist
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.j1iESqK": it needs an instance of "App\\Entity\\Playlist" but this type has been excluded in "config/services.yaml".');
    }
}
