<?php

namespace ContainerCu2R1XU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J1iESqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j1iESqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j1iESqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playlist' => ['privates', '.errored..service_locator.j1iESqK.App\\Entity\\Playlist', NULL, 'Cannot autowire service ".service_locator.j1iESqK": it needs an instance of "App\\Entity\\Playlist" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playlist' => 'App\\Entity\\Playlist',
        ]);
    }
}
