<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYuFdFCZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYuFdFCZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYuFdFCZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYuFdFCZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYuFdFCZ\App_KernelProdContainer([
    'container.build_hash' => 'YuFdFCZ',
    'container.build_id' => 'c518ce0f',
    'container.build_time' => 1774312551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYuFdFCZ');
