<?php

namespace ContainerCg0LYNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminplaylistsControllerService extends App_KernelPantherDebugContainer
{
    /**
     * Gets the public 'App\Controller\admin\AdminplaylistsController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminplaylistsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/admin/AdminplaylistsController.php';

        $container->services['App\\Controller\\admin\\AdminplaylistsController'] = $instance = new \App\Controller\admin\AdminplaylistsController(($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\PlaylistRepository'] ?? $container->load('getPlaylistRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminplaylistsController', $container));

        return $instance;
    }
}
