<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYaU7NuH\App_KernelPantherDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYaU7NuH/App_KernelPantherDebugContainer.php') {
    touch(__DIR__.'/ContainerYaU7NuH.legacy');

    return;
}

if (!\class_exists(App_KernelPantherDebugContainer::class, false)) {
    \class_alias(\ContainerYaU7NuH\App_KernelPantherDebugContainer::class, App_KernelPantherDebugContainer::class, false);
}

return new \ContainerYaU7NuH\App_KernelPantherDebugContainer([
    'container.build_hash' => 'YaU7NuH',
    'container.build_id' => '2c8efb55',
    'container.build_time' => 1774276390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYaU7NuH');
