<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCg0LYNC\App_KernelPantherDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg0LYNC/App_KernelPantherDebugContainer.php') {
    touch(__DIR__.'/ContainerCg0LYNC.legacy');

    return;
}

if (!\class_exists(App_KernelPantherDebugContainer::class, false)) {
    \class_alias(\ContainerCg0LYNC\App_KernelPantherDebugContainer::class, App_KernelPantherDebugContainer::class, false);
}

return new \ContainerCg0LYNC\App_KernelPantherDebugContainer([
    'container.build_hash' => 'Cg0LYNC',
    'container.build_id' => '72493ba1',
    'container.build_time' => 1774310551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg0LYNC');
