<?php

namespace ContainerYuFdFCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCategorieControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\admin\AdminCategorieController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminCategorieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\admin\\AdminCategorieController'] = $instance = new \App\Controller\admin\AdminCategorieController(($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminCategorieController', $container));

        return $instance;
    }
}
