<?php

namespace ContainerYuFdFCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FormationRepository' shared autowired service.
     *
     * @return \App\Repository\FormationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FormationRepository'] = new \App\Repository\FormationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
