<?php

namespace ContainerYuFdFCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PlaylistsController' shared autowired service.
     *
     * @return \App\Controller\PlaylistsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PlaylistsController'] = $instance = new \App\Controller\PlaylistsController(($container->privates['App\\Repository\\PlaylistRepository'] ?? $container->load('getPlaylistRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PlaylistsController', $container));

        return $instance;
    }
}
