<?php

namespace ContainerYuFdFCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PlaylistRepository' shared autowired service.
     *
     * @return \App\Repository\PlaylistRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PlaylistRepository'] = new \App\Repository\PlaylistRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
