<?php

namespace ContainerYuFdFCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PlaylistType' shared autowired service.
     *
     * @return \App\Form\PlaylistType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PlaylistType'] = new \App\Form\PlaylistType();
    }
}
