<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerReoaQds\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerReoaQds/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerReoaQds.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerReoaQds\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerReoaQds\App_KernelTestDebugContainer([
    'container.build_hash' => 'ReoaQds',
    'container.build_id' => 'c5b311d4',
    'container.build_time' => 1774310551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerReoaQds');
