<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZ3WTjA\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZ3WTjA/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPZ3WTjA.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPZ3WTjA\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPZ3WTjA\App_KernelTestDebugContainer([
    'container.build_hash' => 'PZ3WTjA',
    'container.build_id' => '5fcc3446',
    'container.build_time' => 1774276390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZ3WTjA');
