<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2mQtwK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2mQtwK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2mQtwK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2mQtwK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2mQtwK\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2mQtwK',
    'container.build_id' => 'c4856207',
    'container.build_time' => 1774310659,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2mQtwK');
