<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSn01y7y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSn01y7y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSn01y7y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSn01y7y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSn01y7y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sn01y7y',
    'container.build_id' => '6e2386a4',
    'container.build_time' => 1774276392,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSn01y7y');
