<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCu2R1XU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCu2R1XU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCu2R1XU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCu2R1XU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCu2R1XU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cu2R1XU',
    'container.build_id' => 'e362c8cb',
    'container.build_time' => 1774218265,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCu2R1XU');
