
on: push
name: Deploy mediatekformation
jobs:
  web-deploy:
    name: Deploy  to server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
    
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.adjo4744.odns.fr
          username: mediatekformation@mediatekformation.fr
          server-dir: /public_html/mediatekformation/
          password: ${{ secrets.ftp_password }}